# ------------------------
# BESC Hyperchain RPC Node 
# ------------------------

# Data directory
data-path="/var/lib/besu"

# Genesis
genesis-file="/etc/besu/genesis.json"

# P2P
p2p-port=30303
bootnodes=[
  "enode://427acb14e865e4dd2400e6113509e1157ca53fb5bee2ed925c86de4353491e304e8ce9b4f5c9665b35d453fb38fdfc98ba3f00f7ef95af6115e08f5156fddbe6@202.143.109.9:30303"
]

host-allowlist=["*"]

# ---------- HTTP RPC ----------
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=3545
rpc-http-cors-origins=["all"]
rpc-http-api=[
  "ADMIN",
  "CLIQUE",
  "ETH",
  "IBFT",
  "MINER",
  "NET",
  "PERM",
  "PLUGINS",
  "QBFT",
  "TRACE",
  "TXPOOL",
  "WEB3"
]

# ---------- WebSocket RPC ----------
rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-port=3546
rpc-ws-api=[
  "ADMIN",
  "CLIQUE",
  "ETH",
  "IBFT",
  "MINER",
  "NET",
  "PERM",
  "PLUGINS",
  "QBFT",
  "TRACE",
  "TXPOOL",
  "WEB3"
]

# ---------- Gas ----------
min-gas-price=1000000000000
api-gas-price-max=25809520000000

# Logging
logging="INFO"
